name: "Set Issue Label and Assignee"
on:
  issues:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v2.0.0
        with:
          title-or-body: "both"
          parameters: >
            [ 
              {"keywords": ["[suggestion]"], "labels": ["suggestion"]},
              {"keywords": ["[concept]"], "labels": ["concept"]},
              {"keywords": ["[other]"], "labels": ["other"]},
              {"keywords": ["[equipment]", "[equipments]"], "labels": ["equipment"]},
              {"keywords": ["[mission]", "[missions]"], "labels": ["missions"]},
              {"keywords": ["[story]", "[lore]"], "labels": ["story"]},
              {"keywords": ["[music]", "[ost]"], "labels": ["music"]},
              {"keywords": ["[sounds]", "[sounds fx]"], "labels": ["sounds fx"]},
              {"keywords": ["[class]", "[classes]", "[unit]", "[units]", "[classes and units]", "[classes & units]"], "labels": ["classes & units"]}
            ]
